name: news_finder_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  device_preview: ^1.1.0
  shared_preferences: ^2.2.3
  get: 4.6.6
  dio: ^5.4.3+1
  skeletons: ^0.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/png/place_holder.png
  uses-material-design: true

